name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Set up linters
      run: |
        go get golang.org/x/lint/golint
        go get golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow

    - name: Get dependencies
      run: |
        go mod download

    - name: Run linters
      run: |
        # Workaround for https://github.com/actions/setup-go/issues/14 until it is implemented
        export PATH=$PATH:$(go env GOPATH)/bin
        golint ./...
        go vet -vettool=$(which shadow) ./...
        go test -v -race ./...

    - name: Run tests
      run: |
        go test -v -race ./...
